#!/usr/bin/env bash
LOW_LEVEL=20 # in minutes
CRITICAL_LEVEL=10 # in minutes
BATTERY_PATH=/sys/class/power_supply/BAT0

if [ -e "$BATTERY_PATH" ]; then
	BATTERY_ON=$(cat $BATTERY_PATH/status)

	if [ "$BATTERY_ON" == "Discharging" ]; then
		CHARGE_NOW=$(cat $BATTERY_PATH/charge_now)
		CURRENT_NOW=$(cat $BATTERY_PATH/current_now)
		MINUTES_LEFT=$(echo "60*$CHARGE_NOW/$CURRENT_NOW" | bc)

		hrs=$(echo "$MINUTES_LEFT/60" | bc)
		min=$(echo "$MINUTES_LEFT-$hrs*60" | bc)
		DISPLAY_TIME="${hrs}h ${min}min"

		if [ "$MINUTES_LEFT" -lt "$CRITICAL_LEVEL" ]; then
			notify-send -i battery "Out of battery" "Suspending now..."
			sleep 5
			systemctl suspend
		elif [ "$MINUTES_LEFT" -lt "$LOW_LEVEL" ]; then
			for i in {1..3}
			do
				xbacklight -set 10
				sleep 0.5
				xbacklight -set 20
				sleep 0.5
			done
			xbacklight -set 10

			notify-send -i battery "Battery level is low!" "$DISPLAY_TIME remains."
		fi
	fi
fi
