#!/usr/bin/bash
w -hs | grep ':[0-9]\W' | head -1 | awk '{print $(1),$NF}' | while read user cmd; do
	x_pid=$(pgrep -xou "$user" dbus-daemon)
	x_env="/proc/$x_pid/environ"

	if [ -f "$x_env" ]; then
		export $(grep -z DISPLAY $x_env)
		export $(grep -z XAUTHORITY $x_env)
	fi

	if acpi -a | grep -q 'on-line'; then
		su "$user" -c 'xbacklight -set 100'
	else
		su "$user" -c 'xbacklight -set 50'
	fi
done
